import About from '@components/about-section'
import Contact from '@components/contact-section'
import Hero from '@components/hero-section'
import Navbar from '@components/layout/nav'
import Skills from '@components/skills-section'
import Work from '@components/work-section'
import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import { NextPage } from 'next'
import { User } from '@interfaces/User'
import { Repo } from '@interfaces/Repo'
import { fetchRepos, fetchUsers } from 'pages/api/github'
import Repos from '../components/repos-section'


interface Props {
  user: User
  repos: Repo[]
}

const Home : NextPage<Props> = ({user, repos}) => { 

  useEffect(() => {
      }, [])

  return (
    <div>
      <Head>
        <title>Portefolio - Fernando Guimarães</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo192.png' />
      </Head>
      <main>
        <Navbar />
        <Hero/>
        <Repos user={user} repos={repos} />

        <Skills />
        <Work />
      </main>
    </div>
  )
}

Home.getInitialProps = async () => {
  const user = await fetchUsers('guima-seifer')
  const repos = await fetchRepos('guima-seifer')
  return {
    user,
    repos,
  }
}

export default Home