import About from '../components/About'
import Contact from '../components/Contact'
import { Hero } from '../components/Hero'
import { Navbar, NavBarProps} from '../components/Navbar'
import Skills from '../components/Skills'
import Work from '../components/Work'
import React, { useState, useEffect } from 'react'
import Head from 'next/head'

export default function Home() {
  const [darkMode, setDarkMode] = useState<boolean>(false)

  const updateDarkMode = (dark: boolean):void => {
    setDarkMode(dark)
}

  useEffect(() => {
      }, [])
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portefolio - Fernando Guimarães</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo192.png' />
      </Head>
      <main>
        <Navbar updateDarkMode={updateDarkMode} />
        <Hero/>
        <About />
        <Skills />
        <Work />
        <Contact />
      </main>
    </div>
  )
}
